"""add scheduler items ans runners

Revision ID: 6902da2938dd
Revises: 5a580877595d
Create Date: 2021-03-28 18:06:36.884958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6902da2938dd'
down_revision = '5a580877595d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_item_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='item name'),
    sa.Column('pipeline', sa.Text(), nullable=False, comment='pipeline'),
    sa.Column('status', sa.Integer(), nullable=False, comment='item status'),
    sa.Column('interval', sa.Integer(), nullable=False, comment='item interval'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='last runner time'),
    sa.Column('retry_cnt', sa.Integer(), nullable=False, comment='retry count when item is failed'),
    sa.Column('extra', sa.Text(), nullable=True, comment='extra info'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated at'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='deleted at'),
    sa.PrimaryKeyConstraint('id'),
    comment='scheduler items',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_table('scheduler_runner_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('item_id', sa.Integer(), nullable=False, comment='item id'),
    sa.Column('status', sa.Integer(), nullable=False, comment='runner status'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True, comment='runner start time'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='runner end time'),
    sa.Column('pipeline', sa.Text(), nullable=False, comment='pipeline from scheduler item'),
    sa.Column('output', sa.Text(), nullable=False, comment='output'),
    sa.Column('context', sa.Text(), nullable=False, comment='context'),
    sa.Column('extra', sa.Text(), nullable=True, comment='extra info'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated at'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='deleted at'),
    sa.PrimaryKeyConstraint('id'),
    comment='scheduler runners',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_runner_v2')
    op.drop_table('scheduler_item_v2')
    # ### end Alembic commands ###
